@startuml
'https://plantuml.com/class-diagram

class Admin {
firstName:string
secondName:string
}

enum Currency{
UAH,
EUR,
USD
}

class Price{
cost:double
}

interface Product{
getName():string
getPrice():double
getDescription():string
displayProductInfo():void
}

interface ProductFactory{
createProduct(name:string,price:Price,description:string):Product
createProduct(name:string,price:Price,description:string):ProductDto
}

class Electronics{
brand:string
model:string
price:Price
}

class GardenTools{
toolType:string
material:string
price:Price
}

class CarParts{
partNumber:string
compatability:string
price:Price
}

class ElectronicsFactory{
}

class GardenToolsFactory{
}

class CarPartsFactory{
}

class ElectronicsAdapter{
}

class GardenToolsAdapter{
}

class CarPartsAdapter{
}

class AuctionAnnouncement{
creationDate:Date
description:string
}

class Salesman{
firstName:string
secondName:string
phone:string
}

class SaleAnnouncement{
saleDate:Date
description:string
interestRate:double
frequency:string
}

Admin --o AuctionAnnouncement
Product --o AuctionAnnouncement
Currency --o Price
Price --o Electronics
Price --o GardenTools
Price --o CarParts
Salesman --o SaleAnnouncement
Product --o SaleAnnouncement
Electronics --o ElectronicsAdapter
ElectronicsAdapter ..|> Product
GardenTools --o GardenToolsAdapter
GardenToolsAdapter ..|> Product
CarParts --o CarPartsAdapter
CarPartsAdapter ..|> Product
ElectronicsFactory ..|> ProductFactory
GardenToolsFactory ..|> ProductFactory
CarPartsFactory ..|> ProductFactory
@enduml
